import numpy as np
np.random.seed(0)
x1 = np.random.randint(50, size=12)
print('Attributes of the array')
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)
print("dtype:", x1.dtype)
print("itemsize:", x1.itemsize, "bytes")
print("nbytes:", x1.nbytes, "bytes")
print(f"First six elements of the array {x1[:6]}")
print(f"Last six elements of the array {x1[6:]}")
print("Creating a grid using reshape")
grid = x1.reshape((3, 4))
print(grid)
key=int(input('Enter an element to be searched'))
print(f"Found at {np.where(x1==key)}")
print("Array before sorting")
print(x1)
x2=np.sort(x1)
print("Array after sorting")
print(x2)
print("Splitting of array at index 3 and 7")
p,q,r = np.split(x2, [3, 7])
print(p, q, r)
      
